
name: C++ Build and Create Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  BUILD_DIR: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.12.1



    - name: Build C++ program
      run: |
        MSBuild.exe Tools.sln /p:Configuration=Release /p:Platform=x64

    - name: Create Release
      uses: actions/upload-artifact@v2
      with:
        name: Random_Rename
        path: Random_Rename/bin/%BUILD_DIR%/Random_Rename.exe
