
name: C++ Build and Create Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  BUILD_DIR: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSVC Developer Command Prompt
      # You may pin to the exact commit or the version.
      # uses: TheMrMilchmann/setup-msvc-dev@a03e54ab3bbe75ab9bd41f07cc5d30605e70625b
      uses: TheMrMilchmann/setup-msvc-dev@v2.0.0
      with:
        # The target architecture
        arch: amd64,amd64_x86,amd64_arm64
        # optional
        # The path to the Visual Studio installation
        vs-path: .\vs# optional
        # Windows SDK to use
        sdk: 10.0.10240.0# optional
        # Use Visual Studio libraries with Spectre mitigations
        spectre: true# optional
        # VC++ compiler toolset version
        toolset: 17.0 
        # Build for Universal Windows Platform
        uwp: false# optional
        # The environment variable to store the path to vcvarsall.bat in
        export-path-to-vcvarsall: .\1# optional
        # The environment variable to store the path to the Visual Studio installation in
        export-path-to-vs: .\2# optional

    - name: Build C++ program
      run: |
        MSBuild.exe Tools.sln /p:Configuration=%BUILD_DIR% /p:Platform=x64

    - name: Create Release
      uses: actions/upload-artifact@v2
      with:
        name: Random_Rename
        path: Random_Rename/bin/%BUILD_DIR%/Random_Rename.exe
